scalaVersion := "2.12.15"
libraryDependencies += "com.softwaremill.sttp.client" %% "core" % "2.2.10"
libraryDependencies += "com.softwaremill.sttp.client" %% "okhttp-backend" % "2.2.10"
libraryDependencies += "com.lihaoyi" %% "upickle" % "0.7.1"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.12" % "test"
libraryDependencies += "com.github.nscala-time" %% "nscala-time" % "2.30.0"
libraryDependencies += "com.lihaoyi" %% "os-lib" % "0.8.0"
